### ISSUE TITLE
Players die at 4 hearts while using this plugin!

### ISSUE THREAD

**Issue by DanialBrian464** [xkhhv/FastRespawn#2]
Hello there! When iam using this plugin, players die/get teleported at 4 hearts, and the killers dont get the kill/the kill doesnt count! 
It would be wonderful if you can fix this issue!

**Comment by xkhhv** [comment]
Thank you i am working on this...

**Comment by xkhhv** [comment]
For the count for kill i fixed it but i am not sure about it if you can please try it and tell me if it works and for the 4 hearts error it is work for me...

**Comment by TDMidkwhatisxd** [comment]
I use the version from poggit, still cant get STR on FactionsPro because of this plugin

**Comment by xkhhv** [comment]
@TDMidkwhatisxd Give me the link of the plugin

**Comment by TDMidkwhatisxd** [comment]
https://poggit.pmmp.io/p/FactionsPro/1.3.12

**Comment by TDMidkwhatisxd** [comment]
+ not always  u get fast respawned :/
If u lag and enemy hits fast, u get normal respawn
